Loading file. Dataset is the book Mein Kampf by Hitler. Accessed from Project Gutenberg site

In [4]:
filename = r'C:\Users\dell\Desktop\Mein_Kampf.txt'
file=open(filename,'r')
doc=file.read()
file.close()
print(doc[:500])

INTRODUCTION



AUTHOR'S PREFACE

On April 1st, 1924, I began to serve my sentence of detention in the
Fortress of Landsberg am Lech, following the verdict of the Munich
People's Court of that time.

After years of uninterrupted labour it was now possible for the first
time to begin a work which many had asked for and which I myself felt
would be profitable for the Movement. So I decided to devote two volumes
to a description not only of the aims of our Movement but also of its
development. Ther


In [5]:
import nltk
import numpy as np

Attempting to print concordances of a word say, 'Jew'

In [4]:
doc.concordance("Jew")

AttributeError: 'str' object has no attribute 'concordance'

Attempting to load directly from website

In [8]:
from urllib import request
url = "http://gutenberg.net.au/ebooks02/0200601.txt"
response = request.urlopen(url)
raw = response.read().decode('utf8') #incorrect encoding scheme

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 10426: invalid start byte

In [5]:
from urllib import request
url = "http://gutenberg.net.au/ebooks02/0200601.txt"
response = request.urlopen(url)
raw = response.read().decode('iso8859')
type(raw)

str

In [6]:
raw.concordance("Jew")
#concordance is a function under nltk.text

AttributeError: 'str' object has no attribute 'concordance'

In [87]:
f=open(r'C:\Users\dell\Desktop\Meine_Kampf.txt','rU')
raw1=f.read()
#reading text and using nltk tokens to form text so that we can find concordances
tokens = nltk.word_tokenize(raw)
text = nltk.Text(tokens)

C:\Users\dell\Anaconda3_FINAL\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 'U' mode is deprecated
  """Entry point for launching an IPython kernel.


In [88]:
text.concordance("Jew")

Displaying 25 of 211 matches:
rticularly unpleasant for me . In the Jew I still saw only a man who was of a d
ks . My first thought was : Is this a Jew ? They certainly did not have this ap
cultural life , in which at least one Jew did not participate ? On putting the 
aggot in a putrescent body , a little Jew who was often blinded by the sudden l
blooded , thick-skinned and shameless Jew who showed his consummate skill in co
 . But as I learned to track down the Jew in all the different spheres of cultu
 at last to know for certain that the Jew is not a German . Thus I finally disc
 must be devoted to such work . But a Jew can never be rescued from his fixed n
re for you on the following day . The Jew would be utterly oblivious to what ha
nt ! No . The more I came to know the Jew , the easier it was to excuse the wor
 I now understood the language of the Jew . I realized that the Jew uses langua
uage of the Jew . I realized that the Jew uses language for the purpose of diss
 would fin

In [90]:
#for generating some random text. However, the generate() method is not available in NLTK 3.0 but will be reinstated in a subsequent version.
#check https://github.com/nltk/nltk/issues/736
text.generate(words=None)

In [253]:
#cleaning up document
doc = doc.replace('--', ' ')

In [254]:
#Tokenizing
from nltk.tokenize import word_tokenize

tokens=word_tokenize(doc)


In [255]:
#Removing punctuations
tokens = [' ' if w in string.punctuation else w for w in tokens]

In [256]:
#changing to lower case
tokens = [word.lower() for word in tokens]

In [333]:
#printing unique tokens
set(tokens[:200])

{' ',
 "'s",
 '1924',
 '1st',
 'a',
 'about',
 'after',
 'aims',
 'also',
 'am',
 'and',
 'any',
 'april',
 'are',
 'as',
 'asked',
 'author',
 'be',
 'began',
 'begin',
 'belong',
 'but',
 'by',
 'circulated',
 'court',
 'decided',
 'describing',
 'description',
 'destroy',
 'detention',
 'development',
 'devote',
 'doctrinaire',
 'fabrications',
 'far',
 'felt',
 'fewer',
 'first',
 'followers',
 'following',
 'for',
 'fortress',
 'from',
 'given',
 'had',
 'has',
 'have',
 'hearts',
 'i',
 'in',
 'introduction',
 'is',
 'it',
 'its',
 'jewish',
 'know',
 'labour',
 'landsberg',
 'learned',
 'lech',
 'legendary',
 'many',
 'me',
 'more',
 'movement',
 'munich',
 'my',
 'myself',
 'necessary',
 'not',
 'now',
 'of',
 'on',
 'only',
 'opportunity',
 'our',
 'over',
 'own',
 'people',
 'possible',
 'preface',
 'press',
 'profitable',
 'profoundly',
 'purely',
 'second',
 'sentence',
 'serve',
 'so',
 'strangers',
 'study',
 'such',
 'than',
 'that',
 'the',
 'there',
 'this',
 'those',


In [258]:
#finding number of unique tokens
len(set(tokens))

1443

In [259]:
#checking total number of tokens
len(tokens)

5497

In [260]:
#finding lexical diversity
len(set(tokens))/float(len(tokens))

0.2625068219028561

In [261]:
print(tokens[:200])


['introduction', 'author', "'s", 'preface', 'on', 'april', '1st', ' ', '1924', ' ', 'i', 'began', 'to', 'serve', 'my', 'sentence', 'of', 'detention', 'in', 'the', 'fortress', 'of', 'landsberg', 'am', 'lech', ' ', 'following', 'the', 'verdict', 'of', 'the', 'munich', 'people', "'s", 'court', 'of', 'that', 'time', ' ', 'after', 'years', 'of', 'uninterrupted', 'labour', 'it', 'was', 'now', 'possible', 'for', 'the', 'first', 'time', 'to', 'begin', 'a', 'work', 'which', 'many', 'had', 'asked', 'for', 'and', 'which', 'i', 'myself', 'felt', 'would', 'be', 'profitable', 'for', 'the', 'movement', ' ', 'so', 'i', 'decided', 'to', 'devote', 'two', 'volumes', 'to', 'a', 'description', 'not', 'only', 'of', 'the', 'aims', 'of', 'our', 'movement', 'but', 'also', 'of', 'its', 'development', ' ', 'there', 'is', 'more', 'to', 'be', 'learned', 'from', 'this', 'than', 'from', 'any', 'purely', 'doctrinaire', 'treatise', ' ', 'this', 'has', 'also', 'given', 'me', 'the', 'opportunity', 'of', 'describing', 'm

In [264]:
#generating sequences of words that are of length 101 from the tokens. 
#Each sequence is space separated and saved in line. Finally appended to a list called sequences
length = 100 + 1
sequences = list()
for i in range(length, len(tokens)):
    seq = tokens[i-length:i]
    line = ' '.join(seq)
    sequences.append(line)
print('Total Sequences: %d' % len(sequences))

Total Sequences: 5396


In [194]:
#saving sequences to a file
data = '\n'.join(sequences)
file = open("MKSeq.txt", 'w')
file.write(data)
file.close()

In [195]:
file = open("MKSeq.txt", 'r')

text_seq = file.read()
file.close()
lines = text_seq.split('\n')

In [335]:
print(text_seq[:500])

introduction preface on april i began to serve my sentence of detention in the fortress of landsberg am following the verdict of the munich court of that after years of uninterrupted labour it was now possible for the first time to begin a work which many had asked for and which i myself felt would be profitable for the so i decided to devote two volumes to a description not only of the aims of our movement but also of its there is more to be learned from this than from any purely doctrinaire th


In [337]:
#Each unique word must be mapped to an integer  because Keras layers only work on numbers. 
#Thus Tokenizer is used to convert input to sequence of integers.
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(filters='\n')
tokenizer.fit_on_texts(lines) #training and fitting instance tokenizer on lines(text)
sequences = tokenizer.texts_to_sequences(lines) #encodes all training sequences  

Ran into an error--
IndexError: too many indices for array when trying to divide array into X and y 

Possible cause:input is not even and np.array doesn’t parse it properly

In [323]:
#solved using the following
original_sequences = tokenizer.texts_to_sequences(lines)

vocab_size = len(tokenizer.word_index) + 1

aligned_sequneces = []
for sequence in original_sequences:
    aligned_sequence = np.zeros(5401, dtype=np.int64)
    aligned_sequence[:len(sequence)] = np.array(sequence, dtype=np.int64)
    aligned_sequneces.append(aligned_sequence)

sequences = np.array(aligned_sequneces)

In [338]:
vocab_size = len(tokenizer.word_index)
print(vocab_size)

1202


In [205]:
type(sequences)

numpy.ndarray

In [336]:
print(sequences[:500])

[[ 440 1202   20 ...    0    0    0]
 [1202   20 1200 ...    0    0    0]
 [  20 1200   13 ...    0    0    0]
 ...
 [  76   16  281 ...    0    0    0]
 [  16  281    1 ...    0    0    0]
 [ 281    1  115 ...    0    0    0]]


In [339]:
#Separating data to X and y
#X contains all sequences with all words except the last
#y contains all sequences with only the last words
#doing one hot encoding on y so that model can predict the probability distribution for the next word and the ground truth from which to learn from is 0 for all words except the actual word that comes next.
from keras.utils import to_categorical
from numpy import array
sequences = array(sequences)
X, y = sequences[:,:-1], sequences[:,-1]
print(y.shape)
y = to_categorical(y, num_classes=vocab_size)
seq_length = X.shape[1]
print(seq_length)
print(sequences.shape)
print(X.shape)
print(y.shape)

(4306,)
100
(4306, 101)
(4306, 100)
(4306, 1202)


In [278]:
#trying one-hot encoding using sklearn libraries
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(lines)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[1798 2716 2521 ... 1516 2987  196]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [215]:
onehot_encoded.shape

(4306, 4306)

In [151]:
#defining model
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
model = Sequential()
model.add(Embedding(vocab_size, 50, input_length=X.shape[1]))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 5400, 50)          72250     
_________________________________________________________________
lstm_5 (LSTM)                (None, 5400, 100)         60400     
_________________________________________________________________
lstm_6 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_5 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_6 (Dense)              (None, 1445)              145945    
Total params: 369,095
Trainable params: 369,095
Non-trainable params: 0
_________________________________________________________________
None


In [152]:
# compiling model by defining which loss function, optimizer and metrics to use to reduce loss
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fitting model
model.fit(X, y, batch_size=128, epochs=1)

Epoch 1/1
5401/5401 [==============================] - 1634s 302ms/step - loss: 2.9219 - accuracy: 0.9763:22 - loss: 3.8516  - ETA: 45s - loss: 3.0071 - accuracy: 0.97


In [115]:
#saving model checkpoints
model.save('nlp.h5')


In [3]:
#Generating text by first selecting a random line of text from the input text
from random import randint
from pickle import load
seed_text = lines[randint(0,len(lines))]
print(seed_text + '\n')

NameError: name 'lines' is not defined

In [297]:
len(seed_text)

511

In [2]:
seed_text.word_tokenizer()

NameError: name 'seed_text' is not defined

In [327]:
#encoding to sequnce of integer using same tokenizer instance as before
encoded = tokenizer.texts_to_sequences([seed_text])[0]

In [328]:
len(encoded)

101

In [300]:
#converting list to array
arr = np.array(encoded) 
arr.shape

(101,)

In [287]:
X.shape[1]

5400

In [288]:
arr

array([217,  10,   9,   7,  71,   6, 191, 731,   5,  19, 218,   6, 732,
         4,   6, 133,   2, 173,  40,   9, 189,  17,  65,   9, 733,   4,
        39,  68, 338,  19, 734,  51,  10, 735,   2,   1,  13,  73, 163,
         3, 117, 221,   4,   1, 339,  18,  89, 736, 737,   5,  18,  52,
        19, 340,  22, 738,   3, 138,  15,  37, 222, 739,   2,   1,  11,
       223,   9, 123,   3, 740,   3,   1,  36,  61,   5, 223,   3,   1,
        11,  53,  10, 224,  46, 741,  13,   4, 742,   1, 341,  18,   9,
       743,   4,  23, 342, 343,  10,   1, 744, 120,  17])

In [301]:
# padding array with 5299 163's (the mean) because otherwise there is an input shape mismatch
# seed text is only of length 101 but model expects a vector of shape (5400,)
arr=np.pad(arr, (5000,299), 'mean')

In [289]:
# Padding with zeros instead of the mean
arr1=np.pad(arr, (5000,299),'constant')
print(arr)

[217  10   9   7  71   6 191 731   5  19 218   6 732   4   6 133   2 173
  40   9 189  17  65   9 733   4  39  68 338  19 734  51  10 735   2   1
  13  73 163   3 117 221   4   1 339  18  89 736 737   5  18  52  19 340
  22 738   3 138  15  37 222 739   2   1  11 223   9 123   3 740   3   1
  36  61   5 223   3   1  11  53  10 224  46 741  13   4 742   1 341  18
   9 743   4  23 342 343  10   1 744 120  17]


In [302]:
arr.shape

(5400,)

In [290]:
arr1.shape #the zero padded array

(5400,)

In [303]:
#changing array to matrix
mat=np.asmatrix(arr)
mat.shape

(1, 5400)

In [330]:
#converting to matrix the zero padded vector
mat1=np.asmatrix(arr1)
mat1.shape

(1, 5400)

In [329]:
#The error if no padding used and list fed directly
yhat = model.predict_classes(encoded, verbose=0)

ValueError: Error when checking input: expected embedding_4_input to have shape (5400,) but got array with shape (1,)

In [304]:
#solved the problem
yhat = model.predict_classes(mat, verbose=0)

In [314]:
#method to generate the text using mean padded matrix


# generate a sequence from a language model
def generate_seq(model, tokenizer, seq_length, seed_text, n_words):
    result = list()
    in_text = seed_text
    # generate a fixed number of words
    for _ in range(n_words):
        # encode the text as integer
        encoded = tokenizer.texts_to_sequences([in_text])[0]
    
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        np.ravel(encoded)

        yhat = model.predict_classes(encoded, verbose=0)
        # map predicted word index to word
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
# append to input
        in_text += ' ' + out_word
        result.append(out_word)
    return ' '.join(result)

 
# select a seed text
seed_text = lines[randint(0,len(lines))]
print(seed_text + '\n')
 
# generate new text
generated = generate_seq(model, tokenizer, seq_length, seed_text, 100)
print(generated)

gave way to hopes that were better suited to my browsing through my i chanced to come across some publications that dealt with military one of these publications was a popular history of the war of it consisted of two volumes of an illustrated periodical dating from those these became my favourite in a little while that great and heroic conflict began to take first place in my and from that time onwards i became more and more enthusiastic about everything that was in any way connected with war or military but this story of the war had a special significance

                                                                                                   


In [331]:
#method to generate the text using zero padded matrix

# generate a sequence from a language model
def generate_seq(model, tokenizer, seq_length, seed_text, n_words):
    result = list()
    in_text = seed_text
    # generate a fixed number of words
    for _ in range(n_words):
        # encode the text as integer
        encoded = tokenizer.texts_to_sequences([in_text])[0]
    
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        np.ravel(encoded)
        #predicting probabilities of next word
        yhat = model.predict_classes(mat1, verbose=0)
        # map predicted word index to word
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat: #matched integer to word
                out_word = word
                break
# append to input
        in_text += ' ' + out_word
        result.append(out_word)
    return ' '.join(result)

 
# select a seed text
seed_text = lines[randint(0,len(lines))]
print(seed_text + '\n')
 
# generate new text
generated = generate_seq(model, tokenizer, seq_length, seed_text, 100)
print(generated)

october born march claus born august theodor von councillor to the superior provincial born may retired cavalry born may max erwin of born january lorenz ritter born march born october national officials refused to allow the dead heroes a common so i dedicate the first volume of this work to them as a common that the memory of those martyrs may be a permanent source of light for the followers of our the landsberg october introduction in placing before the reader this unabridged translation of adolf mein i feel it my duty to call attention to certain historical facts which must

                                                                                                   
